---

  - name: install grafana-server from a .deb on the internet
    apt:
      deb: '{{ grafana_deb_package }}'
      state: present
    become: true
    register: apt_output
    when: ansible_os_family == 'Debian'

  - name: copy grafana.ini file to /etc/grafana/
    template:
      src: files/grafana.ini
      dest: /etc/grafana/
  

  - name: Copy grafana-server.service to /usr/lib/systemd/system
    template:
      src: grafana-server.service
      dest: /usr/lib/systemd/system/

  - name: Enable Grafana service
    systemd:
      name: grafana-server.service
      enabled: yes
  
  - name: Start grafana service , also issue daemon-reload to pick up config changes
    systemd:
      state: started
      daemon_reload: yes
      name: grafana-server
  